// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	ParentID    pgtype.UUID      `db:"parent_id" json:"parentId"`
	Description *string          `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type Link struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	Url         string           `db:"url" json:"url"`
	Title       string           `db:"title" json:"title"`
	Description string           `db:"description" json:"description"`
	ShortUrl    string           `db:"short_url" json:"shortUrl"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}
